<?php

if(!empty($_SERVER['HTTPS']))
{
	phpinfo(); die();
}

/* Generated by Eregansu Install at 2011-04-19 13:55:50 */

define('INSTANCE_ROOT', realpath(dirname(__FILE__) . '/..') . '/');
define('PUBLIC_ROOT', realpath(dirname(__FILE__)) . '/');

require(INSTANCE_ROOT . '/eregansu/platform.php');

$app->process($request);
