<?php

/* Application configuration for dps-aggregator - generated by Eregansu Install at 2011-09-12 09:25:29*/

define('APP_NAME', 'dps-aggregator');

/* The Redland implementation doesn't work very well in this version of
 * Eregansu
 */
define('EREGANSU_RDF_IMPLEMENTATION', 'phprdf');


/* Trove aggregator */
$SETUP_MODULES[] = 'trove';
$CLI_ROUTES['trove'] = array('name' => 'trove', 'file' => 'cli.php', 'class' => 'TroveCLI', 'description' => 'Trove command-line interface', 'adjustBase' => true);

$TROVE_GENERATORS[] = array('name' => 'trove', 'file' => 'generators/type.php', 'class' => 'TroveTypeGenerator');
$TROVE_GENERATORS[] = array('name' => 'trove', 'file' => 'generators/summary.php', 'class' => 'TroveSummaryGenerator');
$TROVE_GENERATORS[] = array('name' => 'trove', 'file' => 'generators/depiction.php', 'class' => 'TroveDepictionGenerator');
$TROVE_GENERATORS[] = array('name' => 'trove', 'file' => 'generators/refs.php', 'class' => 'TroveRefsGenerator');
$TROVE_GENERATORS[] = array('name' => 'trove', 'file' => 'generators/score.php', 'class' => 'TroveScoreGenerator');
$TROVE_GENERATORS[] = array('name' => 'trove', 'file' => 'generators/geo.php', 'class' => 'TroveGeoGenerator');


/* Trove viewer */
$HTTP_ROUTES['__DEFAULT__'] = array('name' => 'troveview', 'file' => 'home.php', 'class' => 'TroveHomePage');
$HTTP_ROUTES['index'] = array('name' => 'troveview', 'file' => 'home.php', 'class' => 'TroveHomePage');
$HTTP_ROUTES['status'] = array('name' => 'troveview', 'file' => 'status.php', 'class' => 'TroveStatusPage');
$HTTP_ROUTES['collections'] = array('name' => 'troveview', 'file' => 'list.php', 'class' => 'TroveListPage', 'kind' => 'collection', 'title' => 'Collections', 'superior?' => false);
$HTTP_ROUTES['things'] = array('name' => 'troveview', 'file' => 'list.php', 'class' => 'TroveListPage', 'kind' => 'thing', 'title' => 'Things');
$HTTP_ROUTES['people'] = array('name' => 'troveview', 'file' => 'list.php', 'class' => 'TroveListPage', 'kind' => 'person', 'title' => 'People');
$HTTP_ROUTES['places'] = array('name' => 'troveview', 'file' => 'list.php', 'class' => 'TroveListPage', 'kind' => 'place', 'title' => 'Places');
$HTTP_ROUTES['events'] = array('name' => 'troveview', 'file' => 'list.php', 'class' => 'TroveListPage', 'kind' => 'event', 'title' => 'Events');
$HTTP_ROUTES['all'] = array('name' => 'troveview', 'file' => 'list.php', 'class' => 'TroveListPage', 'kind' => array('collection', 'thing', 'person', 'place', 'event'), 'title' => 'All objects');
$HTTP_ROUTES['millennia'] = array('name' => 'troveview', 'file' => 'millennia.php', 'class' => 'TroveMillenniaListPage', 'title' => 'Millennia');
$HTTP_ROUTES['centuries'] = array('name' => 'troveview', 'file' => 'centuries.php', 'class' => 'TroveCenturiesListPage', 'title' => 'Centuries');
$HTTP_ROUTES['decades'] = array('name' => 'troveview', 'file' => 'decades.php', 'class' => 'TroveDecadesListPage', 'title' => 'Centuries');
$HTTP_ROUTES['years'] = array('name' => 'troveview', 'file' => 'years.php', 'class' => 'TroveYearsListPage', 'title' => 'Years');
$HTTP_ROUTES['months'] = array('name' => 'troveview', 'file' => 'months.php', 'class' => 'TroveMonthsListPage', 'title' => 'Months');
$HTTP_ROUTES['ns'] = array('name' => 'troveview', 'file' => 'ns.php', 'class' => 'TroveNamespacePage', 'title' => 'Namespaces');

/* Trove Geonames interface */
$SETUP_MODULES[] = 'geonames';
$TROVE_MATCHING_MODULES[] = 'geonames';
$CLI_ROUTES['geonames-import'] = array('name' => 'geonames', 'file' => 'import.php', 'class' => 'GeonamesImport', 'description' => 'Import geonames data');
$TROVE_PROVIDER_MODULES['GEONAMES_IRI'] = array(
	'name' => 'geonames', 'file' => 'provider.php', 'class' => 'GeonamesProvider', 'importers' => array(
		'geonames_entries' => array('file' => 'import-entry.php'),
	),
);

/* Trove BBC Programmes interface */
$TROVE_MATCHING_MODULES[] = 'bbcprogs';

/* Trove Wikipedia interface */
$TROVE_MATCHING_MODULES[] = 'wikipedia';

